name: Task Validation

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Structure (Debug)
        run: ls -R

      - name: Compile Source
        run: |
          mkdir -p out

          find task-01/src -name "*.java" > sources.txt
          javac -cp "task1/libs/*" -d out @sources.txt

      - name: Compile Tests
        run: |
          find task-01/tests -name "*.java" > tests.txt
          javac -cp "task1/libs/*:out" -d out @tests.txt

      - name: Run Tests
        run: |
          java -cp "task1/libs/*:out" org.junit.runner.JUnitCore Task01Test
